### ISSUE TITLE
directive not working when nested in a cdkDropList

### ISSUE THREAD

**Issue by elazarza** [kreuzerk/ng-sortgrid#105]
when you wrap the ngSortgridItem div with a container that has a cdkDropList directive attached to it, the griditem is not dragging at all.
any suggestions on how to work around this?
thanks!

**Comment by elazarza** [comment]
I checked a bit, and it seems angular is block a bunch of events when using cdkDropList and some of them are dragstart and end, so your package isn't working because it relies on those.

if there is something you can do about it I believe that would come handy to alot of people.

**Comment by kreuzerk** [comment]
Hi @elazarza thx a lot for the issue and the analysis. Yes, we actually rely on those events. If they are suppressed I don't think there's much we can do.
