### ISSUE TITLE
Angular 16 support

### ISSUE THREAD

**Issue by TomSchmanke** [kreuzerk/ng-sortgrid#114]
Hey,
first of all thank you a lot for creating and maintaining this project. You helped my project a lot over the last year.

Do you plan to update the package to Angular 16 and if so do you have an eta for the release?

Thanks a lot.

**Comment by kreuzerk** [comment]
Hi @TomSchmanke, thx a lot for the issue and for using sortgrid. I think I can find some time over lunch today to release an A16-compatible version. I will keep you posted.

Cheers

**Comment by TomSchmanke** [comment]
Thanks a lot. Instantly tried it. Works like a charm for me 👍

**Comment by kreuzerk** [comment]
Awesome. Very happy to hear 👍
