### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by bjornharvold** [kreuzerk/ng-sortgrid#119]
ng-sortgrid did not like that we wanted to upgrade to Angular 18

```
npm error Could not resolve dependency:
npm error peer @angular/common@"^17.0.0" from ng-sortgrid@17.0.0
npm error node_modules/ng-sortgrid
npm error   ng-sortgrid@"17.0.0" from the root project
```

**Comment by tlebreton** [comment]
Hi,

@kreuzerk Is there somethink that need to be done before tagging a new version for ng-sortgrid ?

**Comment by kreuzerk** [comment]
Hey @tlebreton thx a lot for the reminder, usually the publish happens automatically in the pipeline. But there seems to be some error. I just published v18 handish.
