### ISSUE TITLE
working with shift-selection problems

### ISSUE THREAD

**Issue by andreElrico** [kreuzerk/ng-sortgrid#26]
For this we assume the following layout:

```
1 2 3 4  5
6 7 8 9 10
```

1. single item is not always selected (bug)

steps2repoduce: normal click on [1] > then shift click on [1] > [1] is not selected
fix: [1] should be selected

2. SOME NAME FOR THIS POINT (bug)

steps2repoduce: shift click [1] + [2] > normal click [3] and drag > [1] + [2] is dragged
fix: [1] + [2]  should be deselected and [3] should be dragged

3. remove the selection (feature)

steps2repoduce: shift click [1] + [2] > normal click somewhere on the drag grid > nothing happens
fix: [1] + [2] should be deselected

4. moving horizontal selection to edge (bug)

steps2repoduce: shift click [1] + [2] > drag over 5 > results in unexpected order
fix: i expect:

```
3 4 5 1  2
6 7 8 9 10
```
5. moving vertical selection

steps2repoduce: shift click [1] + [6] > drag over 5 > results in unexpected order
fix: i expect: (not entirely sure)

```
2 3 4  5 1
7 8 9 10 6
```

**Comment by kreuzerk** [comment]
@andreElrico with version 3.0.1 the first four points should be fixed. As of point 5, the order should be the following:

````
2 3 4 1 6
5 7 8 9 10
````
