### ISSUE TITLE
Not compatible with lazy loaded projects

### ISSUE THREAD

**Issue by buehler** [kreuzerk/ng-sortgrid#30]
Hey there :-)

I just tried your sort-grid. Sadly, it does not even compile when not using in the root app module. And when using in the root module and then trying to add functionality to a submodule, it does not find the service anymore.

I guess you just need to provide the service in the NgsgModule instead of `root` ?

Then it would be correctly scoped.

LG

**Comment by kreuzerk** [comment]
Hi there, thanks a lot for the feedback. Services provided in ```root``` are also accessible in lazy loaded modules. I just tried it locally and it works.

What's the error? Is there a way to reproduce?

**Comment by buehler** [comment]
Sorry I was trying to reproduce the error, it just happens when I use the service in a lazy loaded Module. The error reads something like " no provider for service found".

But I switched to ng2-dragula which works exactly as I want it to.
