### ISSUE TITLE
Documentation doesn't mentions how to import NgsgModule?

### ISSUE THREAD

**Issue by suhailvs** [kreuzerk/ng-sortgrid#31]
How to import `NgsgModule`? I didn't find documentation any where.

in the example, it is imported like:

`import {NgsgModule} from '../../../../ng-sortgrid/src/lib/ngsg.module'; `

**Comment by kreuzerk** [comment]
NgsgModule can be imported with the following line:

````
import {NgsgModule} from 'ng-sortgrid'
````
I will update the README
