### ISSUE TITLE
Missing CSS file

### ISSUE THREAD

**Issue by btxtiger** [kreuzerk/ng-sortgrid#36]
>  "node_modules/ng-sortgrid/dist/lib/ngsg.css"

The file is not included in the npm package
"ng-sortgrid": "^3.0.1",

![image](https://user-images.githubusercontent.com/15804690/82132318-c319c000-97de-11ea-8aa3-c73bdce1602c.png)

**Comment by btxtiger** [comment]
And as far as I could see in the source code `.ng-sg-active` is not implemented anymore? Should be possible to style the dragged element

**Comment by kreuzerk** [comment]
@btxtiger the css is now included - I will add another ticket for the `.ng-sg-active`
