### ISSUE TITLE
NPM peerDependencies warnings 

### ISSUE THREAD

**Issue by loebi-ch** [kreuzerk/ng-sortgrid#50]
I've just updated to version 4.0.0 of ng-sortgrid.
Unfortunately the following warnings of NPM haven't dissappeared yet:

`npm WARN ng-sortgrid@4.0.0 requires a peer of @angular/common@^7.2.0 but none is installed. You must install peer dependencies yourself.`
`npm WARN ng-sortgrid@4.0.0 requires a peer of @angular/core@^7.2.0 but none is installed. You must install peer dependencies yourself.`

I'm using the newest version of Angular, version 10.0.14.
`"@angular/core": "10.0.14"`
`"@angular/common": "10.0.14"`

Please update your peerDependencies in your package.json.

Best regards,
Andy

**Comment by cedbesafilm** [comment]
![image](https://user-images.githubusercontent.com/55377336/91551002-c36f3e80-e929-11ea-8cbe-188cf113a8f5.png)
