### ISSUE TITLE
Can't install 4.0.1 in Stackblitz - "ngcc failed to run"

### ISSUE THREAD

**Issue by NaughtyPhoton** [kreuzerk/ng-sortgrid#53]
When I try to install latest version in Stackblitz I get an error:

`Error in ~/src/main.ts
ngcc failed to run on ng-sortgrid@4.0.1.`

I also noticed that the latest CI tests failed as well, not sure if they are related:
https://travis-ci.org/github/kreuzerk/ng-sortgrid

Here is an example project:
https://stackblitz.com/edit/ng-sortgrid-tester?file=package.json

<sub>P.S. Thank you for this wonderful library</sub>

**Comment by NaughtyPhoton** [comment]
Upon trying again with the same project it appears to be working.  Must be a misunderstanding on my side..

**Comment by kreuzerk** [comment]
No worries. Glad that it worked. 👍 
PS: The failing CI build originates from the open PR ;)
