### ISSUE TITLE
hi, i meet this error

### ISSUE THREAD

**Issue by webstermobile** [kreuzerk/ng-sortgrid#57]
CommonDemoComponent.html:16 ERROR NullInjectorError: StaticInjectorError(AppModule)[NgsgItemDirective -> NgsgSortService]: 
  StaticInjectorError(Platform: core)[NgsgItemDirective -> NgsgSortService]: 
    NullInjectorError: No provider for NgsgSortService!

**Comment by kiknadze** [comment]
same error in angular 8

**Comment by webstermobile** [comment]
@kreuzerk thanks for your reply , I will upgrade and try again.

**Comment by kreuzerk** [comment]
Hi @webstermobile I guess this issue is solved. I will close this issue for now. Let me know if there are still problems.
