### ISSUE TITLE
Can't find module  - (Angular 11)

### ISSUE THREAD

**Issue by heitorb** [kreuzerk/ng-sortgrid#59]
Can't install with Angular 11... dependency errors when trying to run the npm command in a clean Angular 11 app...

**Comment by isetpro** [comment]
Please, describe your problem in more detail. For instance, what errors did you get? What npm command did you try to run?

**Comment by heitorb** [comment]
It was a clean Angular 11 app. I did not have time to wait I used ngx-sortablejs.
