### ISSUE TITLE
ng-sortgrid functionality broken with Angular version 13.2.4

### ISSUE THREAD

**Issue by loebi-ch** [kreuzerk/ng-sortgrid#87]
Yesterday I updated one of my projects from Angular 13.2.3 to 13.2.4 and I've just realized that ng-sortgrid does not work anymore.

These are the changes made to Angular:
![image](https://user-images.githubusercontent.com/28792333/155684824-ccb3cb08-1b97-4613-bd98-32559c1c0416.png)

**Comment by loebi-ch** [comment]
I'm very sorry for this imprecise bug report.

In the meantime I setup a brand new Angular "Hello World" project and realized that ```ng-sortgrid``` works with Angular version 13.2.4.
So I went deeper in root cause analyses and found out what causes the issue I encountered in my project.

Generally, I use Angular's CDK Drag'n'Drop functionality to make blocks in vertical order sortable. Inside one of these blocks I have a grid that I made sortable with ```ng-sortgrid``` because Angular Drag'n'Drop functionality with ```display: flex; flex-wrap: wrap``` is still a big pain in the ass.

So far this worked like a charm, but with upgrading Angular from version 13.2.3 to 13.2.4 ```ng-sortgrid``` functionality broke completely, because mouse events were not recognized anymore with ```ng-sortgrid```.
When I remove Angular's CDK Drag'n'Drop functionality in the parent's DIV, ```ng-sortgrid``` works again.

I don't have a solution yet, but it has absolutely nothing to do with ```ng-sortgrid```, so I close this issue.

**Comment by kreuzerk** [comment]
@loebi-ch. Wow. Thx a lot for the research and the awesome explanation. Glad to hear that it works. I already started researching a bit but couldn't figure out a solution. But thx to your explanation everything makes perfect sense now. Thx a lot 👍

**Comment by loebi-ch** [comment]
I've found the root cause in Angular's cdk/drag-drop/drag-ref.ts
In Angular CDK version 13.2.4 they've added a line to preventDefault() on dragstart event.

![image](https://user-images.githubusercontent.com/28792333/157005459-fba23f75-8be0-4606-8663-4d72efa1956f.png)

If I comment out the above line again, ```ng-sortgrid``` works again.

**Comment by kreuzerk** [comment]
👍
